version: 0.0
os: linux
files:
    - source: ./server
      destination: /home/ubuntu/smi-express/
permissions:
    - object: /home/ubuntu/smi-express/
      owner: ubuntu
      group: ubuntu
      overwrite: yes
hooks:
    ApplicationStop:
        - location: deploy_scripts/stop_server
          timeout: 300
          runas: root
    BeforeInstall:
        - location: deploy_scripts/reinstall_app
          timeout: 300
          runas: root
    AfterInstall:
        - location: deploy_scripts/install_dependencies
          timeout: 300
          runas: root
    ApplicationStart:
        - location: deploy_scripts/start_server
          timeout: 300
          runas: root
