version: 0.2

phases:
    install:
        commands:
            - npm cache clean --force
            - npm i npm@6.14.6 -g
            - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            - unzip awscliv2.zip
            - sudo ./aws/install

    build:
        commands:
            - echo Build Phase
            - echo Building PWA app
            - cd client
            - aws s3 cp s3://solvemyissue.live-env-files/env.client ./.env
            - npm ci --only=prod
            - npm run build
            # - echo Building Server Side
            # - cd server
            # - npm ci
            # - echo Deploying Server Side
    post_build:
        commands:
            - echo PostBuild Phase
            - echo Pushing to S3
            - aws s3 sync ./dist s3://solvemyissue.live
artifacts:
    files:
        - "server/**/*" #copy all build files + server code to S3 location
